import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { trpc } from '../utils/trpc'
export default function Home() {
  const { data } = trpc.hello.useQuery({
    greeting: 'World'
  })


  const { mutateAsync: createFeedback} = trpc.createFeedback.useMutation() 

  async function handleCreateFeedback(){
    let type = 'bug'
    let comment = 'ykesssss'
    await createFeedback({
      type,
      content: comment
    })
    console.log('sucess')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{data?.message}</h1>
       
      <button onClick={handleCreateFeedback}>
        create feedback
      </button>

    
    </div>
  )
}
